### ISSUE TITLE
Subset data

### ISSUE THREAD

**Issue by pytoPN** [malonzo47/pynita_GUI#18]
Ability to dynamically subset stack in python so that user can run very tiny subsets of their data

**Comment by malonzo47** [comment]
**In Step 3, once the stack is loaded, it would be good to:**
1) search through stack for least cloudy image (see matlab code underneath image)
2) choose that image and display a thumbnail of it (there is plenty of space on this tab)
3) (MAYBE) allow user to hit a "subset" button which would open up image in pop-up window such that user could draw a bounding box for their subset. This subset should probably only be held in memory... right?

![image](https://user-images.githubusercontent.com/15234556/52365270-1c5c4680-2a15-11e9-99d8-a5d72edbdfb7.png)

![image](https://user-images.githubusercontent.com/15234556/52365901-81646c00-2a16-11e9-9947-44ded989f106.png)

**Comment by vasusingla** [comment]
It seems to me, that for python the stack is loaded with the time as 0th dimension, the stack shape for demo data is (459, 45, 71) so am I right in thinking the 0th dimension contains the data?

**Comment by vasusingla** [comment]
Also need some clarity about creating the bounding box? Do users need to subset their data in the x-y dimension? If yes how should I display the plot for this, and only the subsetted data needs to be generated the image metrics for, right?

**Comment by malonzo47** [comment]
Re-prioritized as medium to allow for focus on loading data /hanging processing issues.

**Comment by malonzo47** [comment]
Follow up issues and enhancements re: subsetting:

--Done and Clear buttons are need to be aligned and outside of map data frame

--Update text in step 3: 
"Do you want to spatially subset your data?
Choose small subsets for diagnostic purposes.
You will be presented with least cloudy image from full time series
Note: Subset outputs can be viewed but not saved."

--The bounding box disappears visually onMouseOver the Done or Clear buttons but the functionality does work either way.

--Add a "Clear Subset" button below the "Create Subset" button in Step 3

--Make the "Save" checkboxes in step 4 greyed out, perhaps with a tooltip that reminds user that you can't save a subset

**Comment by malonzo47** [comment]
I am not sure why this was re-opened. If there are issues, I will start a new issue.
