### ISSUE TITLE
data_loader.py doesn't work 

### ISSUE THREAD

**Issue by vasusingla** [malonzo47/pynita_GUI#2]
data_loader.py doesn't work directly if pynita is not installed as a pip package (like in the orignal repository), this functionality is removed in the current repo.

**Comment by vasusingla** [comment]
`from pynita.utils import general `
pynita is no longer installed as a pip package and directory name was modified to pynita_source.
Only requires a minor change in the source code.

**Comment by pytoPN** [comment]
Thanks! Fixed the issue.
