### ISSUE TITLE
need tooltip for value change and date value metric image date ranges

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#27]
Need a tool tip to help user know how to enter in a date. For example, does December 31, 2015 = 2015365 or 2015999? Also, say that 9999 = "end" and -9999 = "beginning will make it so each pixel might have a different start or end date depending on local image-date availability.

**Comment by malonzo47** [comment]
**Tooltip for start date:** "Enter the beginning of your value_change range in the form of yyyyddd. For example, "2015100", for the 100th day of 2015. You can also do -9999 but note that this will allow the ranges to vary, pixel to pixel depending on early-range image availability."

Tool tip for end date: 
"Enter the end of your value_change range in the form of yyyyddd. For example, "2015100", for the 100th day of 2015. You can also do 9999 but note that this will allow the ranges to vary, pixel to pixel depending on late-range image availability."

Tool tip for Date Value: 
"Enter the date for which you'd like to see the VI value at each pixel, in the form of yyyyddd. For example, "2015100", for the 100th day of 2015."

![image](https://user-images.githubusercontent.com/15234556/52364601-a4415100-2a13-11e9-9c03-267011a8c1d0.png)

**Comment by pytoPN** [comment]
Completed
