### ISSUE TITLE
add savitzky golay filter or similar

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#28]
This may not be natively available in a python package but it might be worth building. It has proven useful in Matlab.

**Comment by malonzo47** [comment]
References for Matlab and Python:
Matlab: https://www.mathworks.com/help/signal/ref/sgolayfilt.html
Does this already exist in scipy? There must be some reason we didn’t implement this directly: https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.signal.savgol_filter.html
More scipy: https://scipy-cookbook.readthedocs.io/items/SavitzkyGolay.html

**Comment by vasusingla** [comment]
the functionality is present, but won't work for filt_dist less than or equal to 2, if such value is added it leads to a runtime error which is slightly difficult to debug.

**Comment by malonzo47** [comment]
Ok, it works. I'll close this and open up a related documentation issue.
