### ISSUE TITLE
need to be able to enter metrics parameters in GUI

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#29]
The vi_change_thresh and the run_thresh cannot currently be viewed or set.

**Comment by malonzo47** [comment]
Update: These have been added but the the name for "run_thresh" is incorrect. Should be "run_thresh" but is currently "time_step"

![image](https://user-images.githubusercontent.com/15234556/52364474-4b71b880-2a13-11e9-9295-3f8a967a5023.png)

**Comment by pytoPN** [comment]
Fixed
