### ISSUE TITLE
complexity image not reflecting actual complexity fit

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#32]
The complexity image (demo_dataset) looks mostly random and goes up to 9. The fit show to the right is said to be complexity of "9" per the image. No fits actually have complexity of 9.

![image](https://user-images.githubusercontent.com/15234556/52423164-892f1980-2ac5-11e9-8e53-1b209aeaf0e0.png)

**Comment by vasusingla** [comment]
I might need slight more clarification for this one.

**Comment by malonzo47** [comment]
Check this out for clarification: https://youtu.be/Dp_iuIdqd0c

**Comment by vasusingla** [comment]
This might relate to other issues as well, could we setup a talk for this? I think the issue may be with the axis itself.

**Comment by vasusingla** [comment]
I think I have at least fixed the issue related to the center pixel value, like we had discussed yesterday. As of the complexity image being random...I'm not sure. 
Maybe you can have a look at it Mike? That issue I still believe may be related to strechMI function.

**Comment by malonzo47** [comment]
The axis issue appears to be fixed, which was most important. Contrast stretch is still an "issue" in that the highest values are changed to the 98th percentile highest value. Removing contrast stretch seems worse though. There is probably a better way to only contrast stretch the display itself rather than the data itself (note: this does not effect the data that are saved off by user), but this is lower priority and can be re-opened at a later date.
