### ISSUE TITLE
program hangs on SESYNC server when running nita.py

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#33]
Related to OS and cython code somehow. Working on getting Vasu access to SESYNC server for more direct troubleshooting. Conversation so far:

I had similar issues, but it has something to do with the __pycache__ folder in every folder inside pynita_source folder. I deleted all the __pycache__ folders and also removed the compiled cython code from the distance_funs folder. I re-launched from spyder and it gave error, obviously there is no compiled cython code. I re-copied the compiled code back into distance_funcs folder and restarted the kernel. Along with that, I also stopped the red-button in console and pressed the erase button to remove all stored variables. It worked! As far I see, it only does with windows OS and something to do with cache. Each time you decide to restart the kernel, stop also the red button and use the erase button to remove the cached variables. In that way, you allow spyder to reload all the modules as fresh. Its frustrating, but thats the workaround I discovered so far. 
Cheers,
- Praveen

On Thu, Feb 7, 2019 at 10:16 AM Mike Alonzo <alonzo@american.edu> wrote:
Thanks for the detailed instructions. I was able to follow them without issue. Unfortunately, the sesync install doesn’t work anymore for me. It didn’t work yesterday (with the existing install, for the demo dataset) and did not work last night after I did a fresh setup per the instructions. It hangs forever when running image stacks (or, I assume, also, optimization). Thoughts?
 
Mike

**Comment by vasusingla** [comment]
I believe its not an issue with the cython code per se, but the parallel processing. I tried to run the image metrics on demo dataset on the SESYNC server. I was able to do so without parallelization, but the code hangs in case of parallelization.

**Comment by vasusingla** [comment]
Could you try running the code again with parallelization, ever since I ran it without parallelization enabled I have been able to run the code with parallelization as well. However, I was able to reproduce the bug before this.

**Comment by malonzo47** [comment]
Still hangs for me but possibly in a different place (i.e., with cores working rather than before cores working). See my workflow and issue: https://youtu.be/6qkCsMoml70

UPDATE: The problem is solved still as Praveen notes above. Remove the distance_funs_cython.cp36-win_amd64 file from distance_funs folder, run pynita_gui_main.py code, code fails, put distance_funs_cython.cp36-win_amd64 back in distance_funs folder, run again --> success.

**Comment by vasusingla** [comment]
Fixed the issue, was a problem with spyder IDE, launching through external terminal works fine. Updated README.md for users to configure and follow the instructions.
