### ISSUE TITLE
Progress Bar (Med)

### ISSUE THREAD

**Issue by pytoPN** [malonzo47/pynita_GUI#4]
Progress bar for parallel processing, or at least documentation of how to look at the Task Manager to see cores doing work.

**Comment by malonzo47** [comment]
While a bar that reflects actual percent complete would be ideal, this could be some other means to tell the user: "yes, I'm still working and I'm about x done"

**Comment by vasusingla** [comment]
I've added a functionality for this and raised a pull request, I wasn't sure if it was needed as a GUI based bar or console based. I've added a console based bar for now.
