### ISSUE TITLE
pixel trajectory plots do not pop up when user clicks on pixel in metric image output

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#42]
After user generates (step 3) and displays (step 4) a  metric image, they should be able to click on a pixel and plot the data underneath that pixel. With current spyder config, these plots are getting trapped and are not released until the user plots some other stuff. 

See this quick video to better understand:  https://youtu.be/aTRNRD3qcYY

**Comment by vasusingla** [comment]
Fixed the issue.
