### ISSUE TITLE
Big Tiff issue?

### ISSUE THREAD

**Issue by walteral** [malonzo47/pynita_GUI#47]
Issue When I try and load a some stacks into NITA it returns an error. The image stack I was loading into NITA was: N:\sesync\Walters\pynita_GUI\input\south2018\south_ndmi_stack_01.tif

The stack size is ~500mb. Other larger stacks can get loaded into NITA and this stack has previously run in NITA so I am unsure on how to debug. 

 The error is:

In [2]: nita.loadStack()
Traceback (most recent call last):

  File "<ipython-input-2-c10bffb69777>", line 1, in <module>
    nita.loadStack()

  File "N:\sesync\Walters\pynita_GUI\pynita_source\nita.py", line 61, in loadStack
    self.stack, self.stack_dates, self.stack_doy, self.stack_prj, self.stack_geotransform = dl.load_stack()

  File "N:\sesync\Walters\pynita_GUI\pynita_source\data_reader\data_loader.py", line 80, in load_stack
    stack = fc.ReadAsArray() # t-x-y

AttributeError: 'NoneType' object has no attribute 'ReadAsArray'

**Comment by pytoPN** [comment]
Try deleting associated files with that file, e.g., .xml, etc. and re-run

**Comment by malonzo47** [comment]
There are no associated files. The folder only contains the tif files and
one csv for dates.

**Comment by vasusingla** [comment]
I think I have run into this issue when I used file pts.csv instead of stack_dates.csv. Could you check if this is not the case?

**Comment by malonzo47** [comment]
Not the issue here, I don't think Also happened for Kaspar.

Kaspar's error trying to load 1.7 GB stack:
Python still crashes with my bigger file (1.7 GB) - error message:
    File "D:\Downloads\software\GIS-RS\NITA\pynita_GUI-master\pynita_gui_main.py", line 442, in step3c_runImageStackMetrics
    nita.loadStack()
  File "D:\Downloads\software\GIS-RS\NITA\pynita_GUI-master\pynita_source\nita.py", line 61, in loadStack
    self.stack, self.stack_dates, self.stack_doy, self.stack_prj, self.stack_geotransform = dl.load_stack()
  File "D:\Downloads\software\GIS-RS\NITA\pynita_GUI-master\pynita_source\data_reader\data_loader.py", line 80, in load_stack
    stack = fc.ReadAsArray() # t-x-y
AttributeError: 'NoneType' object has no attribute 'ReadAsArray'

**Comment by malonzo47** [comment]
Here is Kaspar's info:

The python crash occurred with the following files, all in folder ‘N:\sesync\Hurni\input2’:

•	hurni_ndvi_stack2.tif
•	hurni_dates2.csv
•	my_pts_vals.csv
•	user_configs7.ini

**Comment by vasusingla** [comment]
Its issue with conda gdal with BigTIFF format data, will have to look in deeper for a solution

**Comment by malonzo47** [comment]
Relevant? [https://gis.stackexchange.com/questions/291921/cannot-install-a-version-of-gdal-via-anaconda-that-permits-reading-bigtiffs](https://gis.stackexchange.com/questions/291921/cannot-install-a-version-of-gdal-via-anaconda-that-permits-reading-bigtiffs)

**Comment by vasusingla** [comment]
Yeah, I read up on this already, I was trying to download the data, fix on local and then deploy, instead of working on SESYNC server.
