### ISSUE TITLE
hanging when attempting to plot (large?) images

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#48]
After running a large image stack, the saving worked fine but plotting seems problematic. While attempting to plot 2 metric images simultaneously the system hung. I've seen this happen before. Not sure what happens with only one image at this point. It's odd because most of the real work is already done.

**Comment by vasusingla** [comment]
GUI or script?

**Comment by pytoPN** [comment]
If you are trying to plot the old way, then you need to add, `title = "some title"` and `label= "some color label" ` toward the end, 

e.g., 
`nita.MI_postDistSlope(plot=True, save=True, fn='postdistslope.tif', title = title, label=label)`

**Comment by malonzo47** [comment]
This is via GUI

**Comment by pytoPN** [comment]
Is this on sesync machine?

**Comment by vasusingla** [comment]
Also which dataset did you use for this?

**Comment by malonzo47** [comment]
SESYNC machine. Ran the stack in here and  associated dates: N:\sesync\Murillo\input\test_forPyNita

**Comment by vasusingla** [comment]
Can't run this dataset, getting error on data_loader for some reason. Plotting seems to be working fine for small demo image.

**Comment by malonzo47** [comment]
Yeah, this data_loader thing seems to be the main issue (the BigTiff issue
logged for hurni and walters)

**Comment by vasusingla** [comment]
I am having the same issue with this dataset as well, BigTIFF format, fails to load. Was anyone able to run this? If yes, on what machine?

**Comment by malonzo47** [comment]
This dataset we could load/process on sesync via Paulo (but could not load
via Alex) then it hung in step 4.

**Comment by vasusingla** [comment]
I was able to run the Murillo dataset and plot 2 images (disturbance date and disturbance duration) at once. Could you provide an exact way to reproduce? Maybe it got fixed, with the BigTIFF issue?

**Comment by malonzo47** [comment]
I'll try. How long did it take to pop up the images, approximately?

**Comment by vasusingla** [comment]
3-5 sec approx.
BTW - images were on top of each other, so you will need to drag to view.

**Comment by malonzo47** [comment]
I just ran all images (to plot) on this dataset and it took about 1.8 minutes, which is not terrible. I will close this and open new, smaller issue to change check boxes in step 4 (for plotting) to radio buttons.
