### ISSUE TITLE
general error handling

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#49]
This issue may be too broad but we need to handle errors wherein users deviate for the strict workflow without the GUI crashing. One example:
If user specifies a VI (e.g., ndwi) that is not a column in pts.csv then tries to visualize points, the program crashes. Instead, they should be warned to adjust the VI in Step 1.

Should I actually log an issue for each specific workflow?

**Comment by vasusingla** [comment]
yes mike, i will require more specific details, as to where the errors arise.

**Comment by malonzo47** [comment]
Definitely. I was thinking though: Is there a general way such as a
try-catch to deal with as-yet-unknown issues more gracefully? For example,
just reporting error text in a pop-up and forcing user to go back one step
in their workflow? (no idea if that's feasible in reality).

**Comment by vasusingla** [comment]
of course, though i might need to make a lot of changes, the previous code has little exception handling. I've had a lot of crashes myself.

**Comment by malonzo47** [comment]
Closing this in favor of more specific exception handling issues.
