### ISSUE TITLE
date value and custom value change images should have dates in filename

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#53]
Currently, they are just saved as "dateValue.tif" and "valueChange2.tif" and thus are overwritten with any new custom dates.

If user enters 20142000, the dateValue filename should be: "dateValue_2014000.tif"
If user enters custom value change of 2008000 and 2012300 then output should be valueChange_2008000_2012300.tif.

**Comment by vasusingla** [comment]
Will need some clarification for this? In what step are the filenames being changed?

**Comment by malonzo47** [comment]
When saving custom date range images from step 4. Those user-entered dates
should be saved in file names.

**Comment by vasusingla** [comment]
fixed
