### ISSUE TITLE
workflow bug if you plot images then validation points then try to plot images again

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#57]
If you: 1) run an image stack; 2) plot an image (regardless of whether you query a pixel or not); 3) go back to Step 2 and plot points from csv; 3) go back to step 4 and try to plot an output image again. Program crashes.

I'm guessing this has something to do with clearing results_cells or something like this? That is, you've returned to "points analysis" mode and thus somehow cleared out the "image analysis" variables as they might not be adequately separated. 

Update: You don't even need to have plotted an image. The results of Step 3 are not properly retained after revisiting Step 2.

**Comment by vasusingla** [comment]
I have deployed a solution, in the setup_modifications branch, check it out and let me know if it works.
