### ISSUE TITLE
stop reporting when date not in time series

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#59]
For Value Change Custom, if user enters in a start or end date that is beyond the range of data for a pixel, the console will report out as seen in image below. This reporting makes the process of generating an image very long. We should not report this and just produce NoData pixels as required by lack of data.

This is not a problem for "-9999" because if this is entered the algorithm just finds the earliest available data for each pixel.

![image](https://user-images.githubusercontent.com/15234556/58208306-74f8dc00-7cb2-11e9-8bcf-76d25450415c.png)

**Comment by vasusingla** [comment]
Made the update
