### ISSUE TITLE
Python 2.7 conflict with ArcGIS

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#63]
When we run windows_install.bat, I believe it is installing several (or at least) GDAL in python 2.7 because of BigTiff issues with later versions. This is ok in theory but as executed this leads to a python 2.7 conflict with ArcGIS (making scripts in GIS not work). This issue is likely resolved by changing the installer such that it does not automatically update the PATH variable.

**Comment by malonzo47** [comment]
Presumed to be solved by new deployment strategies (e.g., binaries or dockerized source). Confirm and then close.

**Comment by 0xF217** [comment]
If the user already has GDAL installed on the machine, the Docker based method is highly recommended.
Because docker provides a fully self-contained environment (furthermore it is ubuntu based container), it never interferes with the already installed software or packages.
