### ISSUE TITLE
submit button is gray

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#70]
For Step2d and Step3c, if the user runs parallel once, they cannot do it again unless they retype the number of Workers. The submit button should remain accessible without the user needing to do this.

**Comment by 0xF217** [comment]
Enabled the buttons back after finishing the job. But for Step2d, the user still needs to hand-draw the trajectory again to launch the optimization again. Please confirm if this makes sense.

**Comment by malonzo47** [comment]
Yes that's ok. I might make new issue to allow user to save off their hand-drawn trajectories but will close this one.

**Comment by malonzo47** [comment]
In v1.0.2 windows release, this is still not working. I still (Step 3c) need to update the number of cores in order for the Submit button to become active.

**Comment by 0xF217** [comment]
Please check the new [release](https://github.com/malonzo47/pynita_GUI/releases/tag/1.0.3).

**Comment by malonzo47** [comment]
Seems to work in new release.
