### ISSUE TITLE
error running pyNITA from source (docker on windows)

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#71]
Workflow:

1. Download Source Code zip file (https://github.com/malonzo47/pynita_GUI/releases/tag/1.0.2)
2. Move the two .bat files to the pynita_gui_main level
3. run prerequisites.bat
4. run docker_run_windows.bat

During step 4, the script aborts showing the following error:
![image](https://user-images.githubusercontent.com/15234556/76644718-eea5d300-652d-11ea-8467-d55030404e24.png)

**Comment by 0xF217** [comment]
It is failing to configure xming. Please confirm the installation of xming.
Please run prerequiresites.bat as an admin right again and let me know.

**Comment by malonzo47** [comment]
I ran CMD as admin and then ran prerequisites.bat.

![image](https://user-images.githubusercontent.com/15234556/76645355-3a0cb100-652f-11ea-94e6-c65810ec16ec.png)

**Comment by 0xF217** [comment]
I see the reason. As you can see, it did not copy the **config.xlaunch** file. The config.xlaunch file is also contained in the same directory. (`pynita_GUI/installation/docker/windows/`)
Please copy that file to the project root directory and run the bat again. I will change the README accordingly.

**Comment by 0xF217** [comment]
Actually I already specified to **copy all files** in the README.md.
Please check again and confirm.

**Comment by malonzo47** [comment]
Do i somehow need to force reinstall of xming? I just moved the config file and reran both .bat files with the same error.

**Comment by 0xF217** [comment]
No, you do not need to do run both again. Just rerun prerequisites.bat again. And confirm if config.xlaunch file is copied to the user's desktop.

**Comment by malonzo47** [comment]
Yes, it did end up on my desktop.

**Comment by malonzo47** [comment]
Here you can see config on my desktop and how I have the other files organized:
![image](https://user-images.githubusercontent.com/15234556/76646169-e4390880-6530-11ea-916b-225b7d5c89b1.png)

**Comment by 0xF217** [comment]
Press **Win+R** to open a Run dialog and put **notepad c:\windows\system32\drivers\etc\hosts**.
This will open a hosts file. At the end of the file, you will be able to see the parts below.
![screenshot_68](https://user-images.githubusercontent.com/34410700/76647140-7dc9df80-655c-11ea-9dd4-c9d105190c7a.png)


Please comment out the two lines and try again.

**Comment by malonzo47** [comment]
Same error.

**Comment by 0xF217** [comment]
I just updated the **prerequisites.bat**. Please try again.

**Comment by 0xF217** [comment]
The reason was that `xming` was not started after being installed. By adding an additional step at the end of the `prerequisites.bat`, this should be fixed. Closing.
