### ISSUE TITLE
issue running from source 

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#73]
Might be the same/similar as before. This is the develop branch. I accidentally did this setup from master an hour ago and it seemed to work ok. I'm supposed to be using develop, right? This is windows. I've copied the three files to the root and run prerequisites.bat. When I run the docker_windows bat file, I get this:
![image](https://user-images.githubusercontent.com/15234556/77824993-dcef2e80-70dc-11ea-9c28-8596d184b952.png)

**Comment by 0xF217** [comment]
All latest work is maintained on master branch. Please check the develop branch only when I request it.

**Comment by malonzo47** [comment]
Got it. This works then.
