### ISSUE TITLE
progress bar for binary installs

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#74]
To discuss: how difficult would it be to make a progress bar for both Step 2 (optimization) and Step 3 (generate images)? For large datasets the user may be unclear whether there is legitimate progress being made.

**Comment by 0xF217** [comment]
I added two progress bars for step 2d and 3c. Please check the new [release](https://github.com/malonzo47/pynita_GUI/releases/tag/1.0.3)

**Comment by malonzo47** [comment]
I see the progress bars but they show no progress throughout work and then, suddenly, are 100% complete. Needs to properly show incremental progress (similar to the bar that is implemented in the CMD window when running from source).

Also, can this numerically show "% complete"? (Or, if this is ugly or otherwise not great, just label the progress bar as "Progress bar:")

**Comment by 0xF217** [comment]
Fixed on the master branch. Please check running from the source.

**Comment by malonzo47** [comment]
This seems to work running from source. Should I wait to test using a new Windows binary release or just close?

**Comment by 0xF217** [comment]
For now, check only from the source. I will add a new release whenever I think some major issues are resolved.

**Comment by malonzo47** [comment]
Looks good.
