### ISSUE TITLE
back convert distDate image values to better date values

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#75]
Currently the pixel values in the distDate (disturbance date) image output are in the format of 'yyyyddd' which might be fine but the ddd part is from 0-999. This is like it is to accommodate easier math and plotting (a legacy decision that may not have been great).

I would like the final pixel values to be back-converted to a better date format that is amenable to analysis after download by user. Perhaps this is just ddd between 1 and 366 but i'm open to alternative storage formats.

I believe this change would be made in metric_funs.py around line 249
def MI_distDate(metrics_dics, option='middle'):

This back-conversion is already happening for distDuration in same file (line 256).

**Comment by 0xF217** [comment]
Not clear in which step this issue is for.

**Comment by malonzo47** [comment]
Step 4 when plotting disturbance date. I think the pixel value in that image should be yyyyddd but ddd should be between 001 and 366 (instead of 001-999). See code lines referenced above for how we've previously done the back-conversion.

**Comment by 0xF217** [comment]
The follows are what I see when plotting disturbance date and disturbance duration.
Frankly, I don't know the exact meanings of these plots but from the source code part you mentioned the second plot seems to show duration in days while the first one shows specific dates (like 2014156).
Please let me know your thoughts.
![screenshot_12](https://user-images.githubusercontent.com/34410700/80659042-14f4e300-8a88-11ea-8a52-c6bd8b39a6e2.png)

**Comment by 0xF217** [comment]
Please check the latest revision.

**Comment by malonzo47** [comment]
Still a little weird. How are we getting that top value (201691)? If "91" is the day part it always needs to be ddd (091). Every number needs to be either just yyyy or all of yyyyddd.

![image](https://user-images.githubusercontent.com/15234556/80864752-9e581100-8c52-11ea-8753-23bcc28e90be.png)

**Comment by 0xF217** [comment]
Fixed. Please check again.
