### ISSUE TITLE
allow user to specify distdate beginning/middle/end

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#76]
The code allows for users to specify whether they would like to know the disturbance date calculated at the "beginning", "middle", or "end" of a disturbance segment. Currently, the "middle" option is hard-coded into pynita_gui_main around line 1035:
`nita.MI_distDate(**option='middle'**, plot=self.plot3.isChecked(), save=self.save3.isChecked(), fn='distdate.tif', title = title, label=label)`

Users should be able to set this option from the ini file, configured in Step 1 c. Can you add an item to the end of the Step 1 c list for: "dist_date position:"? Then dist_date_pos would be a parameter in the ini file with possible values of beginning, middle, and end.

**Comment by 0xF217** [comment]
Changed. Not sure how to check. Please check using the latest source from the main repository.

**Comment by malonzo47** [comment]
Didn't work. Did you adjust the GUI to accommodate the new parameter (see 2nd paragraph above)?
![image](https://user-images.githubusercontent.com/15234556/80631524-d9c0c880-8a23-11ea-8b60-c5e9e86a1ca9.png)

**Comment by malonzo47** [comment]
Or, wait, is it the opposite, where the ini file is not yet updated. I'll check that now.

**Comment by malonzo47** [comment]
I get this error in Step 4 when I actually try to plot distdate. Note: I did not change the default "middle" value)
![image](https://user-images.githubusercontent.com/15234556/80632379-3375c280-8a25-11ea-84cb-beebaceae971.png)

**Comment by 0xF217** [comment]
Sorry. I pushed again. Please check again.

**Comment by malonzo47** [comment]
Seems to work now. Thanks.
