### ISSUE TITLE
x11 connection broke

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#77]
After some period of time, the containerized program quits because of X11 connection broke. See below. This only seems to happen during period of user inactivity. But it does happen during lengthy processing (as in image below).

![image](https://user-images.githubusercontent.com/15234556/79642617-aa30d700-816c-11ea-9f26-f21a9596ebff.png)

**Comment by malonzo47** [comment]
If you need to use a larger dataset to recreate this issue, here is one:

https://drive.google.com/drive/folders/1lBIRCwAvGjLA8GTFF9M_ImwikMK-KzwU?usp=sharing
image stack = zinda_nbr_stack2.tif
stack dates = zinda_stack_dates2.csv
user_config = user_configs_JJAS.ini

**Comment by 0xF217** [comment]
After a lot of effort, I decided to let this issue to future study. It seems like an issue related to the xming itself. I will work on other issues first and get back to this one later.

**Comment by aesircoin** [comment]
Did you tried this => docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ? 
I could not see the --rm option, but found it for X11 usage. Only an idea.

**Comment by 0xF217** [comment]
I tried. Still the same.

**Comment by 0xF217** [comment]
Just tried again after adding some other flags on docker run command and it seems to work. Please check on your side and let me know.

**Comment by malonzo47** [comment]
I just tried and while it seemed work for longer (processing large image), X11 died as processing reached 100%. I'm not sure if that last point is relevant. I am not just opening up the app and leaving it idle to see what happens.

**Comment by malonzo47** [comment]
Update: still just timed out and crashed after a while. I have another person looking into this issue for now.

**Comment by malonzo47** [comment]
This has never been fully solved. The workaround for now is that one probably shouldn't run long jobs via Docker containers on windows.
