### ISSUE TITLE
make the tooltips actually different for each field, particularly in Step 1

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#80]
But also elsewhere as useful.

**Comment by 0xF217** [comment]
I would appreciate it if you could provide me with the tooltip contents to show on fields that you think necessary.

**Comment by malonzo47** [comment]
Isn't that assigned to me? I haven't written the content yet.

**Comment by 0xF217** [comment]
Sorry, I thought this is assigned to me.

**Comment by malonzo47** [comment]
I've only done this for Step 1 parameters but I think that's ok for now.
