### ISSUE TITLE
DOY range color bar needs to display on all Step 2 and Step 4 scatter plots

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#81]
A colorbar for plots from step 2b needs to always be on the side of the plots. One total per window, regardless of how many plots there are. This should also be the case for when a user clicks on a pixel after displaying a metric image in Step 4.

**Comment by malonzo47** [comment]
This might not actually be an issue for Step 4 plots but definitely Step 2.

**Comment by 0xF217** [comment]
Fixed.
