### ISSUE TITLE
disturbance date color bar and should be long integer not scientific notation

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#82]
See colorbar at right (below). This is being displayed using scientific notation which is not great visually. Please change so that either full yyyyddd displays as long integer or only yyyy (truncated, not rounded) displays.

![image](https://user-images.githubusercontent.com/15234556/80747314-40f87e80-8af1-11ea-9fe7-5f268190bbb4.png)

**Comment by 0xF217** [comment]
Fixed. Please confirm if this revision resolves the issue https://github.com/malonzo47/pynita_GUI/issues/75 too.
