### ISSUE TITLE
issue with colorbar for recovery

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#84]
This is Step 4, running 3-year recovery. Not sure why this scale bar is showing nothing useful. Integer vs. Float issue? 

![image](https://user-images.githubusercontent.com/15234556/80864833-47067080-8c53-11ea-894d-d40ced7f3484.png)

**Comment by 0xF217** [comment]
What were the previous values? I mean what are the reasonable results to be shown?

**Comment by malonzo47** [comment]
The colorbar should simply usefully reflect the range of values displayed in the image. These values will mostly be between 0 and 1 and should be displayed as floating point, probably two digits after the decimal point.

**Comment by 0xF217** [comment]
OK, the problem was that pynita using one function for plotting data (also colorbar). I separated that into 3 types - date, float, standard. Now it seems fine for me. Please check the latest revision on other plots in step4 too.

**Comment by 0xF217** [comment]
Please check if this issue is resolved.

**Comment by malonzo47** [comment]
Looks good.
