### ISSUE TITLE
GDAL version must have libtiff version that supports BigTiff

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#85]
If this is not the case (i.e., with newest version of gdal), then the program will crash when trying to load a large image stack. What's odd though, is that I think this image stack can cause issues even when it's less than 2 GB or 4 GB or whatever the BigTiff threshold is.

Question: Is the relevant gdal version the one that's within python (e.g., Anaconda) or the standalone gdal installed along with OGR?

**Comment by 0xF217** [comment]
After reinstallation of gdal following [this tutorial](https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows) it still fails to allocate memory. 
Also I tried to check BIGTIFF support but the installation I have does not.
`C:\Users\Piao David>gdalinfo --format BIGTIFF
ERROR 1: --format option given with format 'BIGTIFF', but that format not
recognised.  Use the --formats option to get a list of available formats,
and use the short code (i.e. GTiff or HFA) as the format identifier.
`
I am exploring the solution to support BIGTIFF.

**Comment by 0xF217** [comment]
Well, the python WHL package file I use for Windows from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal) include complete GDAL.
![screenshot_57](https://user-images.githubusercontent.com/34410700/81874674-a67f4d00-957e-11ea-95ab-541d6124842f.png)
And checking BigTIFF support from Python using the code below from [Stackoverflow](https://gis.stackexchange.com/questions/291921/cannot-install-a-version-of-gdal-via-anaconda-that-permits-reading-bigtiffs), it seems to be fine.
![screenshot_60](https://user-images.githubusercontent.com/34410700/81874818-0b3aa780-957f-11ea-988b-6b06da05f32e.png)
Do you know how to check if my installation is fine with BIGTIFF format?

(About the memory allocation issue, I still have it and exploring)

**Comment by 0xF217** [comment]
The memory allocation fails at X block offset 1, Y block offset 2. 
Do you have any idea from the image below?
![screenshot_61](https://user-images.githubusercontent.com/34410700/81875173-ff9bb080-957f-11ea-829a-1fce9ecd401e.png)

**Comment by 0xF217** [comment]
Please let me know your python version. I am using x32 and some articles say that x64 version would not have this memory allocation problem.

**Comment by malonzo47** [comment]
I have 64 bit python on 64 bit windows.

**Comment by 0xF217** [comment]
OK, so I believe the memory issue is from that.
With 32bit python, it's limited to allocate 2GB memory at a time and it causes this error.

**Comment by malonzo47** [comment]
I've never seen the memory allocation issue. I can't even tell if this is related to BigTiff or not. What about allocating more RAM like here:

export GDAL_CACHEMAX=4000

no idea if that's useful or not...
(source: https://github.com/tum-gis/cesium-terrain-builder-docker/issues/3)

**Comment by 0xF217** [comment]
I believe this is related to the 32bit/64bit. I tried GDAL_CACHEMAX option and it does not help.

So I want to proceed this way.
- I want you to try the windows installation steps on a fresh new Windows environment (64bit).
- We will resolve the installation steps together.
- I want you to prepare a good example that can test BIGTIFF support status.
- We will resolve BIGTIFF support issue if it fails.

**Comment by malonzo47** [comment]
Since we never actually encountered the BigTiff issue, I will close. The issue was indeed related to 32 bit python and limited memory allocation for large image stacks.
