### ISSUE TITLE
dist_date_pos not showing up in new release

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#87]
In run-from-source, the #16 shows up at bottom but not in v1.0.4 release
![image](https://user-images.githubusercontent.com/15234556/82049811-02cc9480-9685-11ea-9c95-e24b3ef565e3.png)

**Comment by malonzo47** [comment]
Other changes are also not showing up, such as the progress bar in Step 3.

**Comment by 0xF217** [comment]
I uploaded wrong build result. Will upload the latest one soon.

**Comment by 0xF217** [comment]
Release 1.0.4 updated.

**Comment by malonzo47** [comment]
Works
