### ISSUE TITLE
was not able to run exe after build_release

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#88]
The build_release.bat file seemed to go ok (but with many warnings). I did do this within anaconda but using pyinstaller, so not sure if that's an issue...
![image](https://user-images.githubusercontent.com/15234556/82061736-184aba00-9697-11ea-948a-62bd7baaf698.png)

**Comment by 0xF217** [comment]
Please make sure you can run from the source whether you use it in Anaconda or not.

**Comment by malonzo47** [comment]
Ok. Anaconda is making this more complicated and my other computer at work turned itself off! I'll try again later.
