### ISSUE TITLE
gdal dll issues (is this a 32 vs. 64 bit OS issue?)

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#90]
This set of errors occurs when I run pynita_gui_main.py from source (windows 64):
![image](https://user-images.githubusercontent.com/15234556/82664709-47fe4280-9c00-11ea-8500-cc62c6cf0abe.png)

They do not seem to be fatal as I made it through a full workflow. It may relate to the fact that I previously had gdal installed as part of anaconda but then recently removed anaconda. Windows may still have the dll locations from the anaconda install in memory and refuse to look in the right place (even though the path variables are correct). Just my thoughts based mostly on:
https://forum.step.esa.int/t/cant-load-requested-dll-file/8665

But maybe this is a 32 bit vs. 64 bit OS issue?

**Comment by 0xF217** [comment]
>It may relate to the fact that I previously had gdal installed as part of anaconda but then recently removed anaconda. Windows may still have the dll locations from the anaconda install in memory and refuse to look in the right place

I think you are right. Please check the system environment variables and remove the irrelevant ones.
One thing we realized from the previous work is that the project does not need to have gdal installed necessarily.

**Comment by malonzo47** [comment]
The path variable seems to be correct but the issue noted in the link I sent seems to suggest that these old .dll paths might be stored in memory somehow? Not sure how to clear that. I suppose I could just try restarting the computer...

![image](https://user-images.githubusercontent.com/15234556/82672820-dd083800-9c0e-11ea-8142-8275ec7c4f39.png)
